//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchUs.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class WatchUsEntities : DbContext
    {
        public WatchUsEntities()
            : base("name=WatchUsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ws_Device> ws_Device { get; set; }
        public DbSet<ws_DeviceLocation> ws_DeviceLocation { get; set; }
        public DbSet<ws_Event> ws_Event { get; set; }
        public DbSet<ws_mCountryDialingCodes> ws_mCountryDialingCodes { get; set; }
        public DbSet<ws_UserAuthentication> ws_UserAuthentication { get; set; }
        public DbSet<ws_UserEvent> ws_UserEvent { get; set; }
        public DbSet<ws_UserLocation> ws_UserLocation { get; set; }
        public DbSet<ws_UserProfile> ws_UserProfile { get; set; }
        public DbSet<ws_UserGroup> ws_UserGroup { get; set; }
        public DbSet<ws_UserGroupMember> ws_UserGroupMember { get; set; }
        public DbSet<ws_EventStateLookup> ws_EventStateLookup { get; set; }
        public DbSet<ws_EventTypeLookup> ws_EventTypeLookup { get; set; }
        public DbSet<ws_TrackingStateLookup> ws_TrackingStateLookup { get; set; }
        public DbSet<ws_EventAcceptanceStateLookup> ws_EventAcceptanceStateLookup { get; set; }
        public DbSet<ws_UserEventStateLookup> ws_UserEventStateLookup { get; set; }
        public DbSet<ws_UserFeedback> ws_UserFeedback { get; set; }
    
        public virtual ObjectResult<rs_spGetCountryDialingCodes_Result> GetCountryDialingCodes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rs_spGetCountryDialingCodes_Result>("GetCountryDialingCodes");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> AddEvent(string @event)
        {
            var eventParameter = @event != null ?
                new ObjectParameter("event", @event) :
                new ObjectParameter("event", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("AddEvent", eventParameter);
        }
    
        public virtual ObjectResult<string> GetUserLocation(string eventLocationRequest)
        {
            var eventLocationRequestParameter = eventLocationRequest != null ?
                new ObjectParameter("eventLocationRequest", eventLocationRequest) :
                new ObjectParameter("eventLocationRequest", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetUserLocation", eventLocationRequestParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> AddOrUpdateUserGroupMember(string userGroupMember)
        {
            var userGroupMemberParameter = userGroupMember != null ?
                new ObjectParameter("userGroupMember", userGroupMember) :
                new ObjectParameter("userGroupMember", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("AddOrUpdateUserGroupMember", userGroupMemberParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> AddUserGroup(string userGroup)
        {
            var userGroupParameter = userGroup != null ?
                new ObjectParameter("userGroup", userGroup) :
                new ObjectParameter("userGroup", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("AddUserGroup", userGroupParameter);
        }
    
        public virtual int DeleteUserGroup(string userGroup)
        {
            var userGroupParameter = userGroup != null ?
                new ObjectParameter("userGroup", userGroup) :
                new ObjectParameter("userGroup", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUserGroup", userGroupParameter);
        }
    
        public virtual int UpdateUserGroup(string userGroup)
        {
            var userGroupParameter = userGroup != null ?
                new ObjectParameter("userGroup", userGroup) :
                new ObjectParameter("userGroup", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUserGroup", userGroupParameter);
        }
    
        public virtual int SyncUserGroupMembers(string userGroupMember)
        {
            var userGroupMemberParameter = userGroupMember != null ?
                new ObjectParameter("userGroupMember", userGroupMember) :
                new ObjectParameter("userGroupMember", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SyncUserGroupMembers", userGroupMemberParameter);
        }
    
        public virtual ObjectResult<string> GetAllEventsForUser(string eventRequest)
        {
            var eventRequestParameter = eventRequest != null ?
                new ObjectParameter("eventRequest", eventRequest) :
                new ObjectParameter("eventRequest", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetAllEventsForUser", eventRequestParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> AddUserProfile(string userProfile)
        {
            var userProfileParameter = userProfile != null ?
                new ObjectParameter("userProfile", userProfile) :
                new ObjectParameter("userProfile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("AddUserProfile", userProfileParameter);
        }
    
        public virtual int SyncEventParticipants(string @event)
        {
            var eventParameter = @event != null ?
                new ObjectParameter("event", @event) :
                new ObjectParameter("event", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SyncEventParticipants", eventParameter);
        }
    
        public virtual int SyncUserGroupMember(string userGroup)
        {
            var userGroupParameter = userGroup != null ?
                new ObjectParameter("userGroup", userGroup) :
                new ObjectParameter("userGroup", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SyncUserGroupMember", userGroupParameter);
        }
    
        public virtual int UpdateUserProfile(string userProfile)
        {
            var userProfileParameter = userProfile != null ?
                new ObjectParameter("userProfile", userProfile) :
                new ObjectParameter("userProfile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUserProfile", userProfileParameter);
        }
    
        public virtual ObjectResult<string> LeaveUserGroup(string userGroupRequest)
        {
            var userGroupRequestParameter = userGroupRequest != null ?
                new ObjectParameter("userGroupRequest", userGroupRequest) :
                new ObjectParameter("userGroupRequest", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("LeaveUserGroup", userGroupRequestParameter);
        }
    
        public virtual ObjectResult<string> AddUserLocation(string userLocation)
        {
            var userLocationParameter = userLocation != null ?
                new ObjectParameter("userLocation", userLocation) :
                new ObjectParameter("userLocation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("AddUserLocation", userLocationParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> RespondToEventInvite(string eventRequest)
        {
            var eventRequestParameter = eventRequest != null ?
                new ObjectParameter("eventRequest", eventRequest) :
                new ObjectParameter("eventRequest", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("RespondToEventInvite", eventRequestParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> DeleteEvent(string eventRequest)
        {
            var eventRequestParameter = eventRequest != null ?
                new ObjectParameter("eventRequest", eventRequest) :
                new ObjectParameter("eventRequest", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DeleteEvent", eventRequestParameter);
        }
    
        public virtual ObjectResult<string> GetRegisteredContacts(string contactsRequest)
        {
            var contactsRequestParameter = contactsRequest != null ?
                new ObjectParameter("contactsRequest", contactsRequest) :
                new ObjectParameter("contactsRequest", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetRegisteredContacts", contactsRequestParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UpdateEvent(string @event)
        {
            var eventParameter = @event != null ?
                new ObjectParameter("event", @event) :
                new ObjectParameter("event", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UpdateEvent", eventParameter);
        }
    
        public virtual ObjectResult<string> GetUserCountryCode(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetUserCountryCode", userIdParameter);
        }
    
        public virtual int UpdateStatesForEvent(Nullable<System.Guid> eventId)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("eventId", eventId) :
                new ObjectParameter("eventId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStatesForEvent", eventIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ExtendEvent(string eventRequest)
        {
            var eventRequestParameter = eventRequest != null ?
                new ObjectParameter("eventRequest", eventRequest) :
                new ObjectParameter("eventRequest", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ExtendEvent", eventRequestParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> EndEvent(string eventRequest)
        {
            var eventRequestParameter = eventRequest != null ?
                new ObjectParameter("eventRequest", eventRequest) :
                new ObjectParameter("eventRequest", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("EndEvent", eventRequestParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> LeaveEvent(string eventRequest)
        {
            var eventRequestParameter = eventRequest != null ?
                new ObjectParameter("eventRequest", eventRequest) :
                new ObjectParameter("eventRequest", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("LeaveEvent", eventRequestParameter);
        }
    
        public virtual ObjectResult<string> GetEventsInternal(string eventRequest)
        {
            var eventRequestParameter = eventRequest != null ?
                new ObjectParameter("eventRequest", eventRequest) :
                new ObjectParameter("eventRequest", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetEventsInternal", eventRequestParameter);
        }
    
        public virtual ObjectResult<string> GetUserGcmClientId(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetUserGcmClientId", userIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SaveUserFeedback(string userFeedback)
        {
            var userFeedbackParameter = userFeedback != null ?
                new ObjectParameter("userFeedback", userFeedback) :
                new ObjectParameter("userFeedback", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SaveUserFeedback", userFeedbackParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UpdateEventLocation(string eventRequest)
        {
            var eventRequestParameter = eventRequest != null ?
                new ObjectParameter("eventRequest", eventRequest) :
                new ObjectParameter("eventRequest", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UpdateEventLocation", eventRequestParameter);
        }
    
        public virtual ObjectResult<string> GetGcmClientIdForMobile(string gcmClientIdRequest)
        {
            var gcmClientIdRequestParameter = gcmClientIdRequest != null ?
                new ObjectParameter("gcmClientIdRequest", gcmClientIdRequest) :
                new ObjectParameter("gcmClientIdRequest", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetGcmClientIdForMobile", gcmClientIdRequestParameter);
        }
    
        public virtual ObjectResult<string> GetUserEmailId(Nullable<System.Guid> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetUserEmailId", userIdParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> AddTempUserProfile(string userProfile)
        {
            var userProfileParameter = userProfile != null ?
                new ObjectParameter("userProfile", userProfile) :
                new ObjectParameter("userProfile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("AddTempUserProfile", userProfileParameter);
        }
    }
}
