//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchUs.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ws_Event
    {
        public System.Guid EventId { get; set; }
        public int EventTypeId { get; set; }
        public string Description { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Duration { get; set; }
        public System.Guid InitiatorId { get; set; }
        public int TrackingStateId { get; set; }
        public Nullable<System.DateTime> TrackingStopTime { get; set; }
        public Nullable<decimal> DestinationLatitude { get; set; }
        public Nullable<decimal> DestinationLongitude { get; set; }
        public string DestinationName { get; set; }
        public Nullable<bool> IsTrackingRequired { get; set; }
        public Nullable<short> ReminderOffset { get; set; }
        public Nullable<short> TrackingStartOffset { get; set; }
        public int EventStateId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Name { get; set; }
        public int ReminderTypeId { get; set; }
        public string DestinationAddress { get; set; }
        public bool IsQuickEvent { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsRecurring { get; set; }
        public Nullable<int> RecurrenceFrequencyTypeId { get; set; }
        public Nullable<int> RecurrenceCount { get; set; }
        public Nullable<int> RecurrenceFrequency { get; set; }
        public string RecurrenceDaysOfWeek { get; set; }
    }
}
