//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchUs.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ws_UserEvent
    {
        public System.Guid EventId { get; set; }
        public System.Guid UserId { get; set; }
        public bool IsTrackingAccepted { get; set; }
        public Nullable<System.DateTime> TrackingStartTime { get; set; }
        public Nullable<System.DateTime> TrackingEndTime { get; set; }
        public Nullable<int> TrackingEndReason { get; set; }
        public bool IsTrackingActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> UserEventEndTime { get; set; }
        public Nullable<System.Guid> UserGroupId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int EventAcceptanceStateId { get; set; }
        public int UserEventStateId { get; set; }
        public bool IsUserLocationShared { get; set; }
    }
}
