//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchUs.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ws_UserFeedback
    {
        public System.Guid UserFeedbackId { get; set; }
        public System.Guid UserId { get; set; }
        public string Feedback { get; set; }
        public string FeedbackCategory { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UserEmailId { get; set; }
    }
}
